### ISSUE TITLE
Error when running the tests

### ISSUE THREAD

**Issue by informa** [browserstack/node-js-playwright-browserstack#22]
Hi, when following the steps on the readme.md and running `npm run sample-test` I am getting this error:

![Screenshot 2024-05-24 at 1 52 27 PM](https://github.com/browserstack/node-js-playwright-browserstack/assets/726265/09d5ea88-ce3b-4dbe-ba40-c8bf35ec7104)

**Comment by hritik-m** [comment]
Please reach out to browserstack support through support@browserstack.com

**Comment by hritik-m** [comment]
Please reach out to browserstack support through support@browserstack.com

**Comment by informa** [comment]
Sorry, for this, found out via using the nodejs [Selenium](https://www.selenium.dev/) [repo](https://github.com/browserstack/jest-js-browserstack/tree/main) that I didn't have app automation credentials.

Fixed this and now works.
